export interface Project {
    "ID_PROYECTO": number,
    "IMAGEN":  string,
    "NOMBRE_PROYECTO": string,
    "RESUMEN":  string | null,
    "OBJETIVO":  string | null,
    "GRUPO_INVESTIGACION_1": string | null,
    "LINEA_INVESTIGACION_1": string | null,
    "GRUPO_INVESTIGACION_2": string | null,
    "LINEA_INVESTIGACION_2": string | null,
    "GRUPO_INVESTIGACION_3": string | null,
    "LINEA_INVESTIGACION_3": string | null,
    "PROGRAMA_1":  string | null,
    "PROGRAMA_UNIDAD_1": string | null,
    "PROGRAMA_REGION_1":  string | null,
    "PROGRAMA_2": string | null,
    "PROGRAMA_UNIDAD_2": string | null,
    "PROGRAMA_REGION_2": string | null,
    "PROGRAMA_3": string | null,
    "PROGRAMA_UNIDAD_3": string | null,
    "PROGRAMA_REGION_3": string | null,
    "PROGRAMA_4": string | null,
    "PROGRAMA_UNIDAD_4": string | null,
    "PROGRAMA_REGION_4": string | null,
    "PROGRAMA_5": string | null,
    "PROGRAMA_UNIDAD_5": string | null,
    "PROGRAMA_REGION_5": string | null,
    "PROGRAMA_6": string | null,
    "PROGRAMA_UNIDAD_6": string | null,
    "PROGRAMA_REGION_6": string | null,
    "PROGRAMA_7": string | null,
    "PROGRAMA_UNIDAD_7": string | null,
    "PROGRAMA_REGION_7": string | null,
    "PROGRAMA_8": string | null,
    "PROGRAMA_UNIDAD_8": string | null,
    "PROGRAMA_REGION_8": string | null,
    "PROGRAMA_9": string | null,
    "PROGRAMA_UNIDAD_9": string | null,
    "PROGRAMA_REGION_9": string | null,
    "PROGRAMA_10": string | null,
    "PROGRAMA_UNIDAD_10": string | null,
    "PROGRAMA_REGION_10": string | null,
    "PROGRAMA_11": string | null,
    "PROGRAMA_UNIDAD_11": string | null,
    "PROGRAMA_REGION_11": string | null,
    "ADSCRIPCION_1":  string | null,
    "ADSCRIPCION_TIPO_1":  string | null,
    "ADSCRIPCION_2": string | null,
    "ADSCRIPCION_TIPO_2": string | null,
    "ADSCRIPCION_3": string | null,
    "ADSCRIPCION_TIPO_3": string | null,
    "OBJETIVOS_DESARROLLO_SOSTENIBLE":  string | null,
    "DISPONIBLE" : Boolean,
    "ADSCRIPCION_CORREO_1": string | null,
    "ADSCRIPCION_CORREO_2":string | null,
    "ADSCRIPCION_CORREO_3": string | null
}